---
- name: Capture alertmanager alerts
  hosts: localhost
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5050
        data_alerts_path: alerts
        data_host_path: labels.instance
        data_path_separator: .
        skip_original_data: true
  rules:
    - name: SELinux was disabled
      condition: event.alert.labels.alertname == "selinux disabled" and event.alert.status == "firing"
      action:
        run_job_template:
          name: Apply baseline
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
            

    - name: USB device detected
      condition: event.alert.labels.alertname == "USB Device Detected" and event.alert.status == "firing"
      action:
        run_job_template:
          name: 01-js-usb
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
          extra_vars:  
            usb_disable: true

    - name: UserPasswordExpired except Administrato
      condition: event.alert.labels.alertname == "UserPasswordExpired except Administrator" and event.alert.status == "firing"
      action:
        run_job_template:
          name: 01-email-alert
          organization: Default
          job_args:
            limit: "{{ event.meta.hosts }}"
#          extra_vars:  
#            usb_disable: true

    - name: SELinux was enabled
      condition: event.alert.labels.alertname == "selinux disabled" and event.alert.status == "resolved"
      action:
        debug:
          msg: "enabled on: {{ event.meta.hosts }}"
                 

    - name: Capture all other events from this source
      condition: event.alert is defined
      action:
        debug:  
