---
- name: Respond to webhook POST
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - cloin.eda.poster:
            webhook_url:
            search:        
  rules:
    - name: R1 - Heard "Hello!"
      condition: event.payload.message == "Hello!"
      action:
        debug:
          msg: "You said, '{{ event.payload.message }}'. Is it me you're looking for?"

    - name: R2 - Trigger a sftp job file is found"
      condition: event.payload.message is defined and event.payload.message == "file present"
      action:
        run_job_template:
          name: sftp_on_demand
          organization: Default
          #job_args:
          #  limit: "{{ event.meta.hosts }}"